"""
Utility functions for LeetCode Exporter.

Provides helper functions for folder naming, file extension detection,
README generation, CSV export, and statistics computation.
"""

import csv
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from config import LANGUAGE_EXTENSIONS, LANGUAGE_NAMES


def slugify(title: str) -> str:
    """
    Convert a problem title to a URL-safe slug.

    Args:
        title: The problem title (e.g., "Two Sum").

    Returns:
        A hyphenated slug (e.g., "Two-Sum").
    """
    # Remove non-alphanumeric characters except spaces and hyphens
    cleaned = re.sub(r"[^\w\s-]", "", title)
    # Replace whitespace with hyphens
    return re.sub(r"[\s]+", "-", cleaned).strip("-")


def make_folder_name(question_id: str, title: str) -> str:
    """
    Create a standardized folder name for a problem.

    Args:
        question_id: The problem's frontend ID (e.g., "1").
        title: The problem title (e.g., "Two Sum").

    Returns:
        A formatted folder name (e.g., "0001-Two-Sum").
    """
    padded_id = str(question_id).zfill(4)
    slug = slugify(title)
    return f"{padded_id}-{slug}"


def get_file_extension(language: str) -> str:
    """
    Get the file extension for a programming language.

    Args:
        language: The LeetCode language slug (e.g., "python3").

    Returns:
        The file extension including dot (e.g., ".py").
    """
    return LANGUAGE_EXTENSIONS.get(language.lower(), ".txt")


def get_language_name(language: str) -> str:
    """
    Get the human-readable name for a programming language.

    Args:
        language: The LeetCode language slug (e.g., "python3").

    Returns:
        The display name (e.g., "Python 3").
    """
    return LANGUAGE_NAMES.get(language.lower(), language.capitalize())


def format_timestamp(timestamp: int | float | None) -> str:
    """
    Convert a UNIX timestamp to a human-readable date string.

    Args:
        timestamp: UNIX timestamp in seconds, or None.

    Returns:
        Formatted date string (e.g., "2024-01-15"), or "N/A".
    """
    if timestamp is None:
        return "N/A"
    try:
        dt = datetime.fromtimestamp(int(timestamp), tz=timezone.utc)
        return dt.strftime("%Y-%m-%d")
    except (ValueError, OSError):
        return "N/A"


def generate_problem_readme(
    title: str,
    question_id: str,
    difficulty: str,
    tags: list[str],
    title_slug: str,
    language: str,
    timestamp: int | float | None = None,
) -> str:
    """
    Generate a README.md for a single problem folder.

    Args:
        title: Problem title.
        question_id: Frontend problem ID.
        difficulty: Problem difficulty (Easy/Medium/Hard).
        tags: List of topic tags.
        title_slug: URL-friendly problem slug.
        language: Programming language used.
        timestamp: UNIX timestamp of the submission.

    Returns:
        Formatted README markdown string.
    """
    url = f"https://leetcode.com/problems/{title_slug}/"
    tags_str = ", ".join(f"`{tag}`" for tag in tags) if tags else "N/A"
    date_solved = format_timestamp(timestamp)
    lang_name = get_language_name(language)

    # Difficulty badge color
    diff_colors = {"Easy": "#00b8a3", "Medium": "#ffc01e", "Hard": "#ff375f"}
    diff_color = diff_colors.get(difficulty, "#888")

    return f"""# {question_id}. {title}

![Difficulty](https://img.shields.io/badge/{difficulty}-{diff_color.replace('#', '%23')}?style=for-the-badge)

## 📋 Problem

| Property | Value |
|----------|-------|
| **Difficulty** | {difficulty} |
| **Tags** | {tags_str} |
| **Language** | {lang_name} |
| **LeetCode URL** | [{title}]({url}) |
| **Date Solved** | {date_solved} |

## 🔗 Links

- [Problem on LeetCode]({url})
- [Solution](./{make_folder_name(question_id, title)}{get_file_extension(language)})

## 📊 Complexity

| Metric | Complexity |
|--------|------------|
| **Time** | *To be analyzed* |
| **Space** | *To be analyzed* |

---
*Auto-generated by [LeetCode Exporter](https://github.com/)*
"""


def _get_sort_key(p: dict[str, Any]) -> tuple[int, str]:
    """Helper to safely extract a numeric sort key from a question ID."""
    qid = str(p.get("question_id", "0"))
    try:
        return (int(qid), "")
    except ValueError:
        digits = "".join(c for c in qid if c.isdigit())
        return (int(digits) if digits else 0, qid)


def generate_repo_readme(
    problems: list[dict[str, Any]],
    last_updated: str | None = None,
) -> str:
    """
    Generate the repository-level README.md.

    Args:
        problems: List of problem dicts with keys: question_id, title,
                  difficulty, title_slug, language, timestamp.
        last_updated: Optional override for the last-updated timestamp.

    Returns:
        Formatted repository README markdown string.
    """
    total = len(problems)
    easy = sum(1 for p in problems if p.get("difficulty") == "Easy")
    medium = sum(1 for p in problems if p.get("difficulty") == "Medium")
    hard = sum(1 for p in problems if p.get("difficulty") == "Hard")

    # Collect unique languages
    languages = sorted(set(get_language_name(p.get("language", "")) for p in problems))
    languages_str = ", ".join(languages) if languages else "N/A"

    updated = last_updated or datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Sort problems by ID
    sorted_problems = sorted(problems, key=_get_sort_key)

    # Build problem table rows
    table_rows = []
    for p in sorted_problems:
        qid = str(p["question_id"]).zfill(4)
        title = p["title"]
        slug = p["title_slug"]
        diff = p["difficulty"]
        lang = get_language_name(p.get("language", ""))
        folder = make_folder_name(p["question_id"], title)
        url = f"https://leetcode.com/problems/{slug}/"
        date = format_timestamp(p.get("timestamp"))

        table_rows.append(
            f"| {qid} | [{title}]({url}) | [{folder}](./{folder}/) | {diff} | {lang} | {date} |"
        )

    table = "\n".join(table_rows)

    return f"""# 🏆 LeetCode Solutions

<div align="center">

![Total](https://img.shields.io/badge/Total_Solved-{total}-blue?style=for-the-badge)
![Easy](https://img.shields.io/badge/Easy-{easy}-00b8a3?style=for-the-badge)
![Medium](https://img.shields.io/badge/Medium-{medium}-ffc01e?style=for-the-badge)
![Hard](https://img.shields.io/badge/Hard-{hard}-ff375f?style=for-the-badge)

</div>

## 📊 Statistics

| Metric | Count |
|--------|-------|
| **Total Solved** | {total} |
| **Easy** | {easy} |
| **Medium** | {medium} |
| **Hard** | {hard} |
| **Languages** | {languages_str} |
| **Last Updated** | {updated} |

## 📁 Solutions

| # | Problem | Solution | Difficulty | Language | Date |
|---|---------|----------|------------|----------|------|
{table}

---

## 🚀 Setup

This repository is auto-generated by **LeetCode Exporter**.

See the [exporter README](https://github.com/) for setup instructions.

---
*Auto-generated on {updated}*
"""


def export_to_csv(problems: list[dict[str, Any]], output_path: Path) -> Path:
    """
    Export solved problems to a CSV file.

    Args:
        problems: List of problem dictionaries.
        output_path: Directory to save the CSV file.

    Returns:
        Path to the created CSV file.
    """
    csv_path = output_path / "solutions.csv"
    sorted_problems = sorted(problems, key=_get_sort_key)

    fieldnames = [
        "ID", "Title", "Difficulty", "Language", "Tags", "URL", "Date Solved"
    ]

    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for p in sorted_problems:
            writer.writerow({
                "ID": str(p["question_id"]).zfill(4),
                "Title": p["title"],
                "Difficulty": p["difficulty"],
                "Language": get_language_name(p.get("language", "")),
                "Tags": "; ".join(p.get("tags", [])),
                "URL": f"https://leetcode.com/problems/{p['title_slug']}/",
                "Date Solved": format_timestamp(p.get("timestamp")),
            })

    return csv_path


def compute_statistics(problems: list[dict[str, Any]]) -> dict[str, Any]:
    """
    Compute summary statistics for solved problems.

    Args:
        problems: List of problem dictionaries.

    Returns:
        Dictionary containing difficulty and language breakdowns.
    """
    stats: dict[str, Any] = {
        "total": len(problems),
        "by_difficulty": {"Easy": 0, "Medium": 0, "Hard": 0},
        "by_language": {},
    }

    for p in problems:
        diff = p.get("difficulty", "Unknown")
        lang = get_language_name(p.get("language", ""))

        if diff in stats["by_difficulty"]:
            stats["by_difficulty"][diff] += 1

        stats["by_language"][lang] = stats["by_language"].get(lang, 0) + 1

    return stats
